terrafusion_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('PGHOST', 'localhost') }}"
      user: "{{ env_var('PGUSER', 'postgres') }}"
      password: "{{ env_var('PGPASSWORD', 'postgres') }}"
      port: "{{ env_var('PGPORT', '5432') | as_number }}"
      dbname: "{{ env_var('PGDATABASE', 'terradb') }}"
      schema: analytics
      threads: 4