
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-loader
spec:
  replicas: 1
  selector:
    matchLabels: { app: sync-loader }
  template:
    metadata:
      labels: { app: sync-loader }
    spec:
      containers:
        - name: sync-loader
          image: ghcr.io/terrafusion/sync-loader:latest
          env:
            - name: KAFKA_BROKERS
              value: kafka:9092
            - name: TF_DB_URL
              valueFrom:
                secretKeyRef:
                  name: tf-db
                  key: url
