apiVersion: apps/v1
kind: Deployment
metadata:
  name: valuation-wizard
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: valuation-wizard
  template:
    metadata:
      labels:
        app: valuation-wizard
    spec:
      containers:
        - name: wizard
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}