apiVersion: v1
kind: Service
metadata:
  name: valuation-wizard
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: valuation-wizard