global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  - 'recording_rules/*.yml'

scrape_configs:
  - job_name: 'terrafusion-api'
    metrics_path: '/api/metrics/prometheus'
    static_configs:
      - targets: ['localhost:5000']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']