version: 2

models:
  - name: stg_property
    description: "Staged property data from the appraisal schema"
    columns:
      - name: property_id
        description: "Unique identifier for the property"
        tests:
          - not_null
          - unique

  - name: stg_land_parcel
    description: "Staged land parcel data from the appraisal schema"
    columns:
      - name: land_parcel_id
        description: "Unique identifier for the land parcel"
        tests:
          - not_null
          - unique
      - name: property_id
        description: "Foreign key to the property"
        tests:
          - not_null
      - name: type_code
        description: "Code representing the type of land parcel"
      - name: acreage
        description: "Size of the land parcel in acres"
      - name: land_value
        description: "Assessed value of the land parcel"

  - name: stg_improvement
    description: "Staged improvement data from the appraisal schema"
    columns:
      - name: improvement_id
        description: "Unique identifier for the improvement"
        tests:
          - not_null
          - unique
      - name: property_id
        description: "Foreign key to the property"
        tests:
          - not_null
      - name: type_code
        description: "Code representing the type of improvement"
      - name: year_built
        description: "Year the improvement was constructed"
      - name: improvement_value
        description: "Assessed value of the improvement"

  - name: stg_levy
    description: "Staged levy data from the billing schema"
    columns:
      - name: levy_id
        description: "Unique identifier for the tax levy"
        tests:
          - not_null
          - unique
      - name: district_code
        description: "Code representing the tax district"
      - name: authority_name
        description: "Name of the taxing authority"
      - name: levy_year
        description: "Tax year for which the levy applies"
      - name: tax_rate
        description: "Tax rate applied to property valuation"

  - name: stg_levy_bill
    description: "Staged levy bill data from the billing schema"
    columns:
      - name: bill_id
        description: "Unique identifier for the tax bill"
        tests:
          - not_null
          - unique
      - name: property_id
        description: "Foreign key to the property"
        tests:
          - not_null
      - name: levy_id
        description: "Foreign key to the levy"
        tests:
          - not_null
      - name: billed_amount
        description: "Total amount billed"
      - name: due_date
        description: "Date when payment is due"
      - name: status
        description: "Current status of the bill"

  - name: stg_payment
    description: "Staged payment data from the billing schema"
    columns:
      - name: payment_id
        description: "Unique identifier for the payment"
        tests:
          - not_null
          - unique
      - name: bill_id
        description: "Foreign key to the levy bill"
        tests:
          - not_null
      - name: tender_date
        description: "Date when the payment was made"
      - name: payment_amount
        description: "Amount of the payment"

  - name: stg_special_assessment
    description: "Staged special assessment data from the billing schema"
    columns:
      - name: assessment_id
        description: "Unique identifier for the special assessment"
        tests:
          - not_null
          - unique
      - name: property_id
        description: "Foreign key to the property"
        tests:
          - not_null
      - name: agency_code
        description: "Code representing the agency imposing the assessment"
      - name: description
        description: "Description of the special assessment"
      - name: assessment_amount
        description: "Amount of the special assessment"
      - name: start_year
        description: "First year the assessment applies"
      - name: end_year
        description: "Last year the assessment applies"