name: Database Migration Workflow

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'db-migrations/**'
  workflow_dispatch:

jobs:
  validate-migrations:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_database
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Download Flyway
        run: |
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.20.0/flyway-commandline-9.20.0-linux-x64.tar.gz | tar xvz
          sudo ln -s `pwd`/flyway-9.20.0/flyway /usr/local/bin
          
      - name: Validate Migrations
        run: |
          cd db-migrations
          flyway validate -url="jdbc:postgresql://localhost:5432/test_database" -user=postgres -password=postgres
          
      - name: Test Migrations
        run: |
          cd db-migrations
          flyway migrate -url="jdbc:postgresql://localhost:5432/test_database" -user=postgres -password=postgres
          
      - name: Verify Schema
        run: |
          cd db-migrations
          flyway info -url="jdbc:postgresql://localhost:5432/test_database" -user=postgres -password=postgres
          
          # Additional schema verification queries
          PGPASSWORD=postgres psql -h localhost -U postgres -d test_database -c "
          SELECT 
            table_schema,
            COUNT(*) as table_count
          FROM 
            information_schema.tables
          WHERE 
            table_schema IN ('appraisal', 'billing', 'master')
          GROUP BY 
            table_schema
          ORDER BY
            table_schema;
          "
          
          # Verify foreign key constraints
          PGPASSWORD=postgres psql -h localhost -U postgres -d test_database -c "
          SELECT
            tc.table_schema, 
            tc.constraint_name, 
            tc.table_name, 
            kcu.column_name, 
            ccu.table_schema AS foreign_table_schema,
            ccu.table_name AS foreign_table_name,
            ccu.column_name AS foreign_column_name 
          FROM 
            information_schema.table_constraints AS tc 
          JOIN 
            information_schema.key_column_usage AS kcu
              ON tc.constraint_name = kcu.constraint_name
              AND tc.table_schema = kcu.table_schema
          JOIN 
            information_schema.constraint_column_usage AS ccu
              ON ccu.constraint_name = tc.constraint_name
          WHERE 
            tc.constraint_type = 'FOREIGN KEY' AND
            tc.table_schema IN ('appraisal', 'billing', 'master');
          "