-- Database Backup: neondb
-- Date: 2025-04-02T00:50:39.436533
-- Generated by: pg_backup_simple.py


-- Table structure for ai_analysis_request
DROP TABLE IF EXISTS ai_analysis_request CASCADE;
CREATE TABLE ai_analysis_request (
    id integer NOT NULL DEFAULT nextval('ai_analysis_request_id_seq'::regclass),
    user_id integer NOT NULL,
    request_type character varying(64) NOT NULL,
    prompt text NOT NULL,
    parameters json NULL,
    response text NULL,
    ai_response_metadata json NULL,
    processing_time double precision NULL,
    status character varying(32) NULL,
    error_details text NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by_id integer NULL,
    updated_by_id integer NULL,
    PRIMARY KEY (id)
);

-- Table structure for alembic_version
DROP TABLE IF EXISTS alembic_version CASCADE;
CREATE TABLE alembic_version (
    version_num character varying(32) NOT NULL,
    PRIMARY KEY (version_num)
);

-- Data for alembic_version
INSERT INTO alembic_version (version_num) VALUES ('2a3b4c5d6e7f');

-- Table structure for analysis_result
DROP TABLE IF EXISTS analysis_result CASCADE;
CREATE TABLE analysis_result (
    id integer NOT NULL DEFAULT nextval('analysis_result_id_seq'::regclass),
    user_id integer NOT NULL,
    name character varying(128) NOT NULL,
    description text NULL,
    analysis_type character varying(64) NOT NULL,
    parameters json NOT NULL,
    results json NOT NULL,
    visualization_data json NULL,
    start_year integer NOT NULL,
    end_year integer NOT NULL,
    is_public boolean NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by_id integer NULL,
    updated_by_id integer NULL,
    PRIMARY KEY (id)
);

-- Table structure for audit_log
DROP TABLE IF EXISTS audit_log CASCADE;
CREATE TABLE audit_log (
    id integer NOT NULL DEFAULT nextval('audit_log_id_seq'::regclass),
    table_name character varying(255) NOT NULL,
    record_id integer NOT NULL,
    action character varying(50) NOT NULL,
    timestamp timestamp without time zone NULL,
    user_id integer NULL,
    old_values text NULL,
    new_values text NULL,
    ip_address character varying(50) NULL,
    PRIMARY KEY (id)
);

-- Table structure for bill_impact_evaluation
DROP TABLE IF EXISTS bill_impact_evaluation CASCADE;
CREATE TABLE bill_impact_evaluation (
    id integer NOT NULL DEFAULT nextval('bill_impact_evaluation_id_seq'::regclass),
    name character varying(255) NOT NULL,
    description text NULL,
    year integer NOT NULL,
    status character varying(50) NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL,
    PRIMARY KEY (id)
);

-- Table structure for bill_impact_tax_code
DROP TABLE IF EXISTS bill_impact_tax_code CASCADE;
CREATE TABLE bill_impact_tax_code (
    id integer NOT NULL DEFAULT nextval('bill_impact_tax_code_id_seq'::regclass),
    evaluation_id integer NOT NULL,
    tax_code character varying(20) NOT NULL,
    current_rate double precision NOT NULL,
    proposed_rate double precision NOT NULL,
    percent_change double precision NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL,
    PRIMARY KEY (id)
);

-- Table structure for compliance_check
DROP TABLE IF EXISTS compliance_check CASCADE;
CREATE TABLE compliance_check (
    id integer NOT NULL DEFAULT nextval('compliance_check_id_seq'::regclass),
    tax_code_id integer NOT NULL,
    check_date timestamp without time zone NULL,
    check_type character varying(50) NOT NULL,
    is_compliant boolean NOT NULL,
    details text NULL,
    year integer NOT NULL,
    PRIMARY KEY (id)
);

-- Table structure for compliance_issue
DROP TABLE IF EXISTS compliance_issue CASCADE;
CREATE TABLE compliance_issue (
    id integer NOT NULL DEFAULT nextval('compliance_issue_id_seq'::regclass),
    tax_district_id integer NOT NULL,
    issue_type character varying(64) NOT NULL,
    severity character varying(32) NOT NULL,
    description text NOT NULL,
    impact_amount double precision NULL,
    resolution_status character varying(32) NULL,
    resolution_notes text NULL,
    resolved_at timestamp without time zone NULL,
    resolved_by_id integer NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by_id integer NULL,
    updated_by_id integer NULL,
    year integer NOT NULL,
    PRIMARY KEY (id)
);

-- Table structure for compliance_report
DROP TABLE IF EXISTS compliance_report CASCADE;
CREATE TABLE compliance_report (
    id integer NOT NULL DEFAULT nextval('compliance_report_id_seq'::regclass),
    report_date timestamp without time zone NULL,
    report_type character varying(50) NOT NULL,
    year integer NOT NULL,
    overall_compliant boolean NOT NULL,
    compliance_percentage double precision NULL,
    critical_issues text NULL,
    report_data text NOT NULL,
    created_by integer NULL,
    PRIMARY KEY (id)
);

-- Table structure for data_archive
DROP TABLE IF EXISTS data_archive CASCADE;
CREATE TABLE data_archive (
    id integer NOT NULL DEFAULT nextval('data_archive_id_seq'::regclass),
    archive_type character varying(50) NOT NULL,
    table_name character varying(255) NOT NULL,
    archive_date timestamp without time zone NULL,
    retention_date timestamp without time zone NULL,
    data text NOT NULL,
    record_count integer NOT NULL,
    created_by integer NULL,
    description text NULL,
    status character varying(50) NULL,
    PRIMARY KEY (id)
);

-- Table structure for district_forecast
DROP TABLE IF EXISTS district_forecast CASCADE;
CREATE TABLE district_forecast (
    id integer NOT NULL DEFAULT nextval('district_forecast_id_seq'::regclass),
    district_id integer NOT NULL,
    created_at timestamp without time zone NULL,
    model_type character varying(50) NOT NULL,
    scenario character varying(50) NOT NULL,
    years_ahead integer NOT NULL,
    base_year integer NOT NULL,
    tax_codes text NOT NULL,
    aggregate_forecast text NOT NULL,
    is_published boolean NULL,
    name character varying(255) NULL,
    description text NULL,
    created_by integer NULL,
    PRIMARY KEY (id)
);

-- Table structure for export_log
DROP TABLE IF EXISTS export_log CASCADE;
CREATE TABLE export_log (
    id integer NOT NULL DEFAULT nextval('export_log_id_seq'::regclass),
    filename character varying(255) NOT NULL,
    rows_exported integer NOT NULL,
    export_date timestamp without time zone NULL,
    export_type character varying(50) NULL,
    status character varying(50) NULL DEFAULT 'completed'::character varying,
    notes text NULL,
    PRIMARY KEY (id)
);

-- Data for export_log
INSERT INTO export_log (id, filename, rows_exported, export_date, export_type, status, notes) VALUES (1, 'sample_tax_roll_20250401.csv', 12, '2025-04-01 01:55:42.827151', NULL, 'completed', NULL);
INSERT INTO export_log (id, filename, rows_exported, export_date, export_type, status, notes) VALUES (2, 'tax_roll_test.csv', 4764, '2025-03-17 04:51:25.144018', NULL, 'completed', NULL);

-- Table structure for forecast
DROP TABLE IF EXISTS forecast CASCADE;
CREATE TABLE forecast (
    id integer NOT NULL DEFAULT nextval('forecast_id_seq'::regclass),
    user_id integer NOT NULL,
    name character varying(128) NOT NULL,
    description text NULL,
    tax_district_id integer NULL,
    tax_code_id integer NULL,
    base_year integer NOT NULL,
    forecast_years integer NULL,
    model_type character varying(64) NOT NULL,
    model_parameters json NULL,
    forecast_data json NULL,
    accuracy_metrics json NULL,
    confidence_intervals json NULL,
    is_public boolean NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by_id integer NULL,
    updated_by_id integer NULL,
    PRIMARY KEY (id)
);

-- Table structure for forecast_model
DROP TABLE IF EXISTS forecast_model CASCADE;
CREATE TABLE forecast_model (
    id integer NOT NULL DEFAULT nextval('forecast_model_id_seq'::regclass),
    tax_code character varying(20) NOT NULL,
    created_at timestamp without time zone NULL,
    model_type character varying(50) NOT NULL,
    scenario character varying(50) NOT NULL,
    years_ahead integer NOT NULL,
    base_year integer NOT NULL,
    historical_data text NOT NULL,
    forecast_data text NOT NULL,
    metrics text NULL,
    is_published boolean NULL,
    name character varying(255) NULL,
    description text NULL,
    created_by integer NULL,
    PRIMARY KEY (id)
);

-- Table structure for glossary_term
DROP TABLE IF EXISTS glossary_term CASCADE;
CREATE TABLE glossary_term (
    id integer NOT NULL DEFAULT nextval('glossary_term_id_seq'::regclass),
    term character varying(128) NOT NULL,
    definition text NOT NULL,
    example text NULL,
    related_terms text NULL,
    category character varying(64) NULL,
    source character varying(256) NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by_id integer NULL,
    updated_by_id integer NULL,
    PRIMARY KEY (id)
);

-- Table structure for import_log
DROP TABLE IF EXISTS import_log CASCADE;
CREATE TABLE import_log (
    id integer NOT NULL DEFAULT nextval('import_log_id_seq'::regclass),
    filename character varying(255) NOT NULL,
    records_imported integer NOT NULL,
    records_skipped integer NOT NULL,
    warnings text NULL,
    import_date timestamp without time zone NULL,
    import_type character varying(50) NULL,
    status character varying(50) NULL DEFAULT 'completed'::character varying,
    notes text NULL,
    user_id integer NULL,
    PRIMARY KEY (id)
);

-- Data for import_log
INSERT INTO import_log (id, filename, records_imported, records_skipped, warnings, import_date, import_type, status, notes, user_id) VALUES (1, 'sample_property_data.csv', 12, 0, NULL, '2025-04-01 01:55:36.211600', 'property', 'completed', NULL, NULL);
INSERT INTO import_log (id, filename, records_imported, records_skipped, warnings, import_date, import_type, status, notes, user_id) VALUES (2, 'property_data_test.csv', 1832, 33, NULL, '2025-03-02 04:51:25.144018', 'property', 'completed', NULL, NULL);
INSERT INTO import_log (id, filename, records_imported, records_skipped, warnings, import_date, import_type, status, notes, user_id) VALUES (3, 'district_data_test.xml', 171, 10, NULL, '2025-02-15 04:51:25.144018', 'district', 'completed', NULL, NULL);

-- Table structure for levy_rate
DROP TABLE IF EXISTS levy_rate CASCADE;
CREATE TABLE levy_rate (
    id integer NOT NULL DEFAULT nextval('levy_rate_id_seq'::regclass),
    tax_district_id integer NOT NULL,
    levy_rate double precision NOT NULL,
    levy_amount double precision NOT NULL,
    assessed_value_basis double precision NOT NULL,
    is_final boolean NULL,
    notes text NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by_id integer NULL,
    updated_by_id integer NULL,
    year integer NOT NULL,
    PRIMARY KEY (id)
);

-- Table structure for levy_scenario
DROP TABLE IF EXISTS levy_scenario CASCADE;
CREATE TABLE levy_scenario (
    id integer NOT NULL DEFAULT nextval('levy_scenario_id_seq'::regclass),
    name character varying(100) NOT NULL,
    description text NULL,
    created_at timestamp without time zone NULL,
    created_by character varying(100) NULL,
    base_year integer NOT NULL,
    is_active boolean NOT NULL,
    PRIMARY KEY (id)
);

-- Table structure for levy_scenario_adjustment
DROP TABLE IF EXISTS levy_scenario_adjustment CASCADE;
CREATE TABLE levy_scenario_adjustment (
    id integer NOT NULL DEFAULT nextval('levy_scenario_adjustment_id_seq'::regclass),
    scenario_id integer NOT NULL,
    tax_code_id integer NOT NULL,
    adjustment_type character varying(50) NOT NULL,
    adjustment_value double precision NOT NULL,
    PRIMARY KEY (id)
);

-- Table structure for property
DROP TABLE IF EXISTS property CASCADE;
CREATE TABLE property (
    id integer NOT NULL DEFAULT nextval('property_id_seq'::regclass),
    property_id character varying(64) NOT NULL,
    assessed_value double precision NOT NULL,
    tax_code character varying(20) NOT NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL,
    address character varying(255) NULL,
    owner_name character varying(255) NULL,
    property_type character varying(50) NULL,
    year integer NULL DEFAULT EXTRACT(year FROM CURRENT_DATE),
    PRIMARY KEY (id)
);

-- Data for property
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (1, '12345678', 450000.0, 'BNTCTY', '2025-04-01 01:55:35.130176', '2025-04-01 01:55:35.130180', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (2, '12345679', 550000.0, 'KENN', '2025-04-01 01:55:35.223138', '2025-04-01 01:55:35.223142', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (3, '12345680', 350000.0, 'PROSSER', '2025-04-01 01:55:35.308980', '2025-04-01 01:55:35.308983', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (4, '12345681', 650000.0, 'RICH', '2025-04-01 01:55:35.394499', '2025-04-01 01:55:35.394502', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (5, '12345682', 850000.0, 'COUNTY', '2025-04-01 01:55:35.480180', '2025-04-01 01:55:35.480183', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (6, '12345683', 425000.0, 'FIRE1', '2025-04-01 01:55:35.565997', '2025-04-01 01:55:35.566001', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (7, '12345684', 375000.0, 'KENNHOSP', '2025-04-01 01:55:35.651770', '2025-04-01 01:55:35.651774', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (8, '12345685', 925000.0, 'MCLIB', '2025-04-01 01:55:35.737866', '2025-04-01 01:55:35.737869', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (9, '12345686', 575000.0, 'PORTBNT', '2025-04-01 01:55:35.823961', '2025-04-01 01:55:35.823964', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (10, '12345687', 625000.0, 'PTKEN', '2025-04-01 01:55:35.909505', '2025-04-01 01:55:35.909509', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (11, '12345688', 725000.0, 'BNTCTYLIB', '2025-04-01 01:55:35.995308', '2025-04-01 01:55:35.995312', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (12, '12345689', 825000.0, 'WBNTFIRE', '2025-04-01 01:55:36.081937', '2025-04-01 01:55:36.081940', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (13, 'PROP-BNTCTY-1', 250000.0, 'BNTCTY', '2025-04-01 04:18:07.103917', '2025-04-01 04:18:07.103921', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (14, 'PROP-BNTCTY-2', 300000.0, 'BNTCTY', '2025-04-01 04:18:07.185757', '2025-04-01 04:18:07.185761', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (15, 'PROP-BNTCTY-3', 350000.0, 'BNTCTY', '2025-04-01 04:18:07.263551', '2025-04-01 04:18:07.263554', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (16, 'PROP-BNTCTY-4', 400000.0, 'BNTCTY', '2025-04-01 04:18:07.341271', '2025-04-01 04:18:07.341275', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (17, 'PROP-BNTCTY-5', 450000.0, 'BNTCTY', '2025-04-01 04:18:07.419037', '2025-04-01 04:18:07.419041', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (18, 'PROP-KENN-1', 250000.0, 'KENN', '2025-04-01 04:18:07.496770', '2025-04-01 04:18:07.496774', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (19, 'PROP-KENN-2', 300000.0, 'KENN', '2025-04-01 04:18:07.574567', '2025-04-01 04:18:07.574570', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (20, 'PROP-KENN-3', 350000.0, 'KENN', '2025-04-01 04:18:07.652597', '2025-04-01 04:18:07.652600', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (21, 'PROP-KENN-4', 400000.0, 'KENN', '2025-04-01 04:18:07.730449', '2025-04-01 04:18:07.730452', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (22, 'PROP-KENN-5', 450000.0, 'KENN', '2025-04-01 04:18:07.808184', '2025-04-01 04:18:07.808189', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (23, 'PROP-PROSSER-1', 250000.0, 'PROSSER', '2025-04-01 04:18:07.885958', '2025-04-01 04:18:07.885962', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (24, 'PROP-PROSSER-2', 300000.0, 'PROSSER', '2025-04-01 04:18:07.963852', '2025-04-01 04:18:07.963855', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (25, 'PROP-PROSSER-3', 350000.0, 'PROSSER', '2025-04-01 04:18:08.041948', '2025-04-01 04:18:08.041951', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (26, 'PROP-PROSSER-4', 400000.0, 'PROSSER', '2025-04-01 04:18:08.119865', '2025-04-01 04:18:08.119869', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (27, 'PROP-PROSSER-5', 450000.0, 'PROSSER', '2025-04-01 04:18:08.198156', '2025-04-01 04:18:08.198160', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (28, 'PROP-RICH-1', 250000.0, 'RICH', '2025-04-01 04:18:08.277929', '2025-04-01 04:18:08.277932', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (29, 'PROP-RICH-2', 300000.0, 'RICH', '2025-04-01 04:18:08.355953', '2025-04-01 04:18:08.355957', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (30, 'PROP-RICH-3', 350000.0, 'RICH', '2025-04-01 04:18:08.434307', '2025-04-01 04:18:08.434310', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (31, 'PROP-RICH-4', 400000.0, 'RICH', '2025-04-01 04:18:08.512137', '2025-04-01 04:18:08.512140', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (32, 'PROP-RICH-5', 450000.0, 'RICH', '2025-04-01 04:18:08.589734', '2025-04-01 04:18:08.589738', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (33, 'PROP-COUNTY-1', 250000.0, 'COUNTY', '2025-04-01 04:18:08.667492', '2025-04-01 04:18:08.667495', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (34, 'PROP-COUNTY-2', 300000.0, 'COUNTY', '2025-04-01 04:18:08.745306', '2025-04-01 04:18:08.745310', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (35, 'PROP-COUNTY-3', 350000.0, 'COUNTY', '2025-04-01 04:18:08.823601', '2025-04-01 04:18:08.823606', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (36, 'PROP-COUNTY-4', 400000.0, 'COUNTY', '2025-04-01 04:18:08.901445', '2025-04-01 04:18:08.901449', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (37, 'PROP-COUNTY-5', 450000.0, 'COUNTY', '2025-04-01 04:18:08.979462', '2025-04-01 04:18:08.979467', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (38, 'PROP-FIRE1-1', 250000.0, 'FIRE1', '2025-04-01 04:18:09.057591', '2025-04-01 04:18:09.057595', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (39, 'PROP-FIRE1-2', 300000.0, 'FIRE1', '2025-04-01 04:18:09.135282', '2025-04-01 04:18:09.135286', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (40, 'PROP-FIRE1-3', 350000.0, 'FIRE1', '2025-04-01 04:18:09.213139', '2025-04-01 04:18:09.213143', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (41, 'PROP-FIRE1-4', 400000.0, 'FIRE1', '2025-04-01 04:18:09.290675', '2025-04-01 04:18:09.290678', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (42, 'PROP-FIRE1-5', 450000.0, 'FIRE1', '2025-04-01 04:18:09.368842', '2025-04-01 04:18:09.368846', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (43, 'PROP-KENNHOSP-1', 250000.0, 'KENNHOSP', '2025-04-01 04:18:09.447087', '2025-04-01 04:18:09.447091', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (44, 'PROP-KENNHOSP-2', 300000.0, 'KENNHOSP', '2025-04-01 04:18:09.525025', '2025-04-01 04:18:09.525029', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (45, 'PROP-KENNHOSP-3', 350000.0, 'KENNHOSP', '2025-04-01 04:18:09.603150', '2025-04-01 04:18:09.603154', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (46, 'PROP-KENNHOSP-4', 400000.0, 'KENNHOSP', '2025-04-01 04:18:09.681259', '2025-04-01 04:18:09.681263', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (47, 'PROP-KENNHOSP-5', 450000.0, 'KENNHOSP', '2025-04-01 04:18:09.759261', '2025-04-01 04:18:09.759265', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (48, 'PROP-MCLIB-1', 250000.0, 'MCLIB', '2025-04-01 04:18:09.837086', '2025-04-01 04:18:09.837090', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (49, 'PROP-MCLIB-2', 300000.0, 'MCLIB', '2025-04-01 04:18:09.915776', '2025-04-01 04:18:09.915780', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (50, 'PROP-MCLIB-3', 350000.0, 'MCLIB', '2025-04-01 04:18:09.993624', '2025-04-01 04:18:09.993628', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (51, 'PROP-MCLIB-4', 400000.0, 'MCLIB', '2025-04-01 04:18:10.072173', '2025-04-01 04:18:10.072178', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (52, 'PROP-MCLIB-5', 450000.0, 'MCLIB', '2025-04-01 04:18:10.150175', '2025-04-01 04:18:10.150179', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (53, 'PROP-PORTBNT-1', 250000.0, 'PORTBNT', '2025-04-01 04:18:10.227774', '2025-04-01 04:18:10.227778', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (54, 'PROP-PORTBNT-2', 300000.0, 'PORTBNT', '2025-04-01 04:18:10.306264', '2025-04-01 04:18:10.306268', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (55, 'PROP-PORTBNT-3', 350000.0, 'PORTBNT', '2025-04-01 04:18:10.384425', '2025-04-01 04:18:10.384428', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (56, 'PROP-PORTBNT-4', 400000.0, 'PORTBNT', '2025-04-01 04:18:10.462273', '2025-04-01 04:18:10.462277', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (57, 'PROP-PORTBNT-5', 450000.0, 'PORTBNT', '2025-04-01 04:18:10.540434', '2025-04-01 04:18:10.540437', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (58, 'PROP-PTKEN-1', 250000.0, 'PTKEN', '2025-04-01 04:18:10.618594', '2025-04-01 04:18:10.618598', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (59, 'PROP-PTKEN-2', 300000.0, 'PTKEN', '2025-04-01 04:18:10.696610', '2025-04-01 04:18:10.696614', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (60, 'PROP-PTKEN-3', 350000.0, 'PTKEN', '2025-04-01 04:18:10.775026', '2025-04-01 04:18:10.775030', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (61, 'PROP-PTKEN-4', 400000.0, 'PTKEN', '2025-04-01 04:18:10.853383', '2025-04-01 04:18:10.853387', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (62, 'PROP-PTKEN-5', 450000.0, 'PTKEN', '2025-04-01 04:18:10.931571', '2025-04-01 04:18:10.931575', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (63, 'PROP-BNTCTYLIB-1', 250000.0, 'BNTCTYLIB', '2025-04-01 04:18:11.009852', '2025-04-01 04:18:11.009857', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (64, 'PROP-BNTCTYLIB-2', 300000.0, 'BNTCTYLIB', '2025-04-01 04:18:11.088364', '2025-04-01 04:18:11.088368', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (65, 'PROP-BNTCTYLIB-3', 350000.0, 'BNTCTYLIB', '2025-04-01 04:18:11.167097', '2025-04-01 04:18:11.167102', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (66, 'PROP-BNTCTYLIB-4', 400000.0, 'BNTCTYLIB', '2025-04-01 04:18:11.245716', '2025-04-01 04:18:11.245719', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (67, 'PROP-BNTCTYLIB-5', 450000.0, 'BNTCTYLIB', '2025-04-01 04:18:11.324029', '2025-04-01 04:18:11.324033', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (68, 'PROP-WBNTFIRE-1', 250000.0, 'WBNTFIRE', '2025-04-01 04:18:11.402579', '2025-04-01 04:18:11.402583', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (69, 'PROP-WBNTFIRE-2', 300000.0, 'WBNTFIRE', '2025-04-01 04:18:11.481665', '2025-04-01 04:18:11.481669', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (70, 'PROP-WBNTFIRE-3', 350000.0, 'WBNTFIRE', '2025-04-01 04:18:11.559612', '2025-04-01 04:18:11.559616', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (71, 'PROP-WBNTFIRE-4', 400000.0, 'WBNTFIRE', '2025-04-01 04:18:11.643576', '2025-04-01 04:18:11.643580', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (72, 'PROP-WBNTFIRE-5', 450000.0, 'WBNTFIRE', '2025-04-01 04:18:11.721726', '2025-04-01 04:18:11.721730', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (73, 'PROP-TC-001-1', 250000.0, 'TC-001', '2025-04-01 04:18:11.799929', '2025-04-01 04:18:11.799933', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (74, 'PROP-TC-001-2', 300000.0, 'TC-001', '2025-04-01 04:18:11.878400', '2025-04-01 04:18:11.878403', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (75, 'PROP-TC-001-3', 350000.0, 'TC-001', '2025-04-01 04:18:11.956428', '2025-04-01 04:18:11.956432', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (76, 'PROP-TC-001-4', 400000.0, 'TC-001', '2025-04-01 04:18:12.034410', '2025-04-01 04:18:12.034414', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (77, 'PROP-TC-001-5', 450000.0, 'TC-001', '2025-04-01 04:18:12.112945', '2025-04-01 04:18:12.112949', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (78, 'PROP-TC-002-1', 250000.0, 'TC-002', '2025-04-01 04:18:12.190775', '2025-04-01 04:18:12.190778', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (79, 'PROP-TC-002-2', 300000.0, 'TC-002', '2025-04-01 04:18:12.268785', '2025-04-01 04:18:12.268789', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (80, 'PROP-TC-002-3', 350000.0, 'TC-002', '2025-04-01 04:18:12.346756', '2025-04-01 04:18:12.346760', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (81, 'PROP-TC-002-4', 400000.0, 'TC-002', '2025-04-01 04:18:12.424784', '2025-04-01 04:18:12.424787', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (82, 'PROP-TC-002-5', 450000.0, 'TC-002', '2025-04-01 04:18:12.502704', '2025-04-01 04:18:12.502707', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (83, 'PROP-TC-003-1', 250000.0, 'TC-003', '2025-04-01 04:18:12.580637', '2025-04-01 04:18:12.580641', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (84, 'PROP-TC-003-2', 300000.0, 'TC-003', '2025-04-01 04:18:12.658350', '2025-04-01 04:18:12.658354', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (85, 'PROP-TC-003-3', 350000.0, 'TC-003', '2025-04-01 04:18:12.736443', '2025-04-01 04:18:12.736447', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (86, 'PROP-TC-003-4', 400000.0, 'TC-003', '2025-04-01 04:18:12.814185', '2025-04-01 04:18:12.814188', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (87, 'PROP-TC-003-5', 450000.0, 'TC-003', '2025-04-01 04:18:12.892095', '2025-04-01 04:18:12.892098', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (88, 'PROP-TC-004-1', 250000.0, 'TC-004', '2025-04-01 04:18:12.970248', '2025-04-01 04:18:12.970252', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (89, 'PROP-TC-004-2', 300000.0, 'TC-004', '2025-04-01 04:18:13.048197', '2025-04-01 04:18:13.048200', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (90, 'PROP-TC-004-3', 350000.0, 'TC-004', '2025-04-01 04:18:13.126214', '2025-04-01 04:18:13.126218', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (91, 'PROP-TC-004-4', 400000.0, 'TC-004', '2025-04-01 04:18:13.204347', '2025-04-01 04:18:13.204350', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (92, 'PROP-TC-004-5', 450000.0, 'TC-004', '2025-04-01 04:18:13.282131', '2025-04-01 04:18:13.282135', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (93, 'PROP-TC-005-1', 250000.0, 'TC-005', '2025-04-01 04:18:13.360072', '2025-04-01 04:18:13.360075', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (94, 'PROP-TC-005-2', 300000.0, 'TC-005', '2025-04-01 04:18:13.439499', '2025-04-01 04:18:13.439502', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (95, 'PROP-TC-005-3', 350000.0, 'TC-005', '2025-04-01 04:18:13.517486', '2025-04-01 04:18:13.517489', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (96, 'PROP-TC-005-4', 400000.0, 'TC-005', '2025-04-01 04:18:13.595870', '2025-04-01 04:18:13.595874', NULL, NULL, NULL, 2025);
INSERT INTO property (id, property_id, assessed_value, tax_code, created_at, updated_at, address, owner_name, property_type, year) VALUES (97, 'PROP-TC-005-5', 450000.0, 'TC-005', '2025-04-01 04:18:13.673863', '2025-04-01 04:18:13.673867', NULL, NULL, NULL, 2025);

-- Table structure for report_template
DROP TABLE IF EXISTS report_template CASCADE;
CREATE TABLE report_template (
    id integer NOT NULL DEFAULT nextval('report_template_id_seq'::regclass),
    name character varying(255) NOT NULL,
    type character varying(50) NOT NULL,
    sections text NOT NULL,
    sorting text NULL,
    filters text NULL,
    description text NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL,
    created_by integer NULL,
    is_public boolean NULL,
    PRIMARY KEY (id)
);

-- Table structure for scheduled_report
DROP TABLE IF EXISTS scheduled_report CASCADE;
CREATE TABLE scheduled_report (
    id integer NOT NULL DEFAULT nextval('scheduled_report_id_seq'::regclass),
    template_id integer NOT NULL,
    format character varying(50) NOT NULL,
    frequency character varying(50) NOT NULL,
    day character varying(50) NULL,
    time character varying(50) NULL,
    recipients text NULL,
    subject character varying(255) NULL,
    is_active boolean NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL,
    created_by integer NULL,
    last_run timestamp without time zone NULL,
    next_run timestamp without time zone NULL,
    PRIMARY KEY (id)
);

-- Table structure for system_setting
DROP TABLE IF EXISTS system_setting CASCADE;
CREATE TABLE system_setting (
    id integer NOT NULL DEFAULT nextval('system_setting_id_seq'::regclass),
    key character varying(128) NOT NULL,
    value text NULL,
    value_type character varying(32) NULL,
    description text NULL,
    updated_at timestamp without time zone NULL,
    updated_by_id integer NULL,
    PRIMARY KEY (id)
);

-- Table structure for tax_code
DROP TABLE IF EXISTS tax_code CASCADE;
CREATE TABLE tax_code (
    id integer NOT NULL DEFAULT nextval('tax_code_id_seq'::regclass),
    code character varying(20) NOT NULL,
    levy_amount double precision NULL,
    levy_rate double precision NULL,
    previous_year_rate double precision NULL,
    total_assessed_value double precision NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL,
    description character varying(255) NULL,
    year integer NULL DEFAULT EXTRACT(year FROM CURRENT_DATE),
    PRIMARY KEY (id)
);

-- Data for tax_code
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (1, 'BNTCTY', 1000000.0, 5.5, 5.3415, 200000000.0, '2025-04-01 01:55:36.522163', '2025-04-01 04:51:25.254278', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (2, 'KENN', 800000.0, 5.2, 5.1613, 150000000.0, '2025-04-01 01:55:36.611074', '2025-04-01 04:51:25.254283', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (3, 'PROSSER', 600000.0, 4.8, 4.7633, 120000000.0, '2025-04-01 01:55:36.697901', '2025-04-01 04:51:25.254283', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (4, 'RICH', 750000.0, 5.0, 4.958, 135000000.0, '2025-04-01 01:55:36.812655', '2025-04-01 04:51:25.254284', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (5, 'COUNTY', 1200000.0, 5.8, 5.7462, 220000000.0, '2025-04-01 01:55:36.898904', '2025-04-01 04:51:25.254287', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (6, 'FIRE1', 300000.0, 4.2, 4.0669, 70000000.0, '2025-04-01 01:55:36.985482', '2025-04-01 04:51:25.254288', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (7, 'KENNHOSP', 500000.0, 4.5, 4.456, 110000000.0, '2025-04-01 01:55:37.072215', '2025-04-01 04:51:25.254288', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (8, 'MCLIB', 400000.0, 4.4, 4.3586, 95000000.0, '2025-04-01 01:55:37.158686', '2025-04-01 04:51:25.254289', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (9, 'PORTBNT', 450000.0, 4.6, 4.5754, 100000000.0, '2025-04-01 01:55:37.244666', '2025-04-01 04:51:25.254289', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (10, 'PTKEN', 550000.0, 4.7, 4.6546, 115000000.0, '2025-04-01 01:55:37.330866', '2025-04-01 04:51:25.254290', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (11, 'BNTCTYLIB', 350000.0, 4.3, 4.1006, 80000000.0, '2025-04-01 01:55:37.416937', '2025-04-01 04:51:25.254290', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (12, 'WBNTFIRE', 250000.0, 4.1, 4.0694, 60000000.0, '2025-04-01 01:55:37.502981', '2025-04-01 04:51:25.254291', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (13, 'TC-001', 100000.0, 10.0, 9.9353, 10000000.0, '2025-04-01 04:18:06.548476', '2025-04-01 04:51:25.254291', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (14, 'TC-002', 75000.0, 15.0, 14.8723, 5000000.0, '2025-04-01 04:18:06.633173', '2025-04-01 04:51:25.254292', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (15, 'TC-003', 140000.0, 7.0, 6.933, 20000000.0, '2025-04-01 04:18:06.711246', '2025-04-01 04:51:25.254292', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (16, 'TC-004', 50000.0, 5.0, 4.8591, 10000000.0, '2025-04-01 04:18:06.788919', '2025-04-01 04:51:25.254292', NULL, 2025);
INSERT INTO tax_code (id, code, levy_amount, levy_rate, previous_year_rate, total_assessed_value, created_at, updated_at, description, year) VALUES (17, 'TC-005', 25000.0, 5.0, 4.9705, 5000000.0, '2025-04-01 04:18:06.866595', '2025-04-01 04:51:25.254293', NULL, 2025);

-- Table structure for tax_code_historical_rate
DROP TABLE IF EXISTS tax_code_historical_rate CASCADE;
CREATE TABLE tax_code_historical_rate (
    id integer NOT NULL DEFAULT nextval('tax_code_historical_rate_id_seq'::regclass),
    tax_code_id integer NOT NULL,
    year integer NOT NULL,
    levy_rate double precision NOT NULL,
    levy_amount double precision NULL,
    total_assessed_value double precision NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL,
    PRIMARY KEY (id)
);

-- Table structure for tax_district
DROP TABLE IF EXISTS tax_district CASCADE;
CREATE TABLE tax_district (
    id integer NOT NULL DEFAULT nextval('tax_district_temp_id_seq'::regclass),
    year integer NOT NULL,
    district_name character varying(128) NOT NULL,
    district_code character varying(16) NOT NULL,
    district_type character varying(64) NULL,
    county character varying(64) NULL,
    state character varying(2) NULL,
    description text NULL,
    is_active boolean NULL,
    contact_name character varying(128) NULL,
    contact_email character varying(128) NULL,
    contact_phone character varying(20) NULL,
    statutory_limit double precision NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by_id integer NULL,
    updated_by_id integer NULL,
    PRIMARY KEY (id)
);

-- Data for tax_district
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (1, 2017, 'Unknown District', 'BNTCTY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:37.778879', '2025-04-01 01:55:37.778884', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (4, 2017, 'Unknown District', 'PROSSER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.042836', '2025-04-01 01:55:38.042841', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (5, 2017, 'Unknown District', 'RICH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.129195', '2025-04-01 01:55:38.129198', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (9, 2017, 'Unknown District', 'ROAD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.474914', '2025-04-01 01:55:38.474919', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (10, 2017, 'Unknown District', 'FIRE1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.560981', '2025-04-01 01:55:38.560984', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (11, 2017, 'Unknown District', 'KENNHOSP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.646852', '2025-04-01 01:55:38.646856', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (12, 2017, 'Unknown District', 'MCLIB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.732711', '2025-04-01 01:55:38.732714', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (13, 2017, 'Unknown District', 'PORTBNT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.818510', '2025-04-01 01:55:38.818513', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (14, 2017, 'Unknown District', 'PTKEN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.904352', '2025-04-01 01:55:38.904356', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (15, 2017, 'Unknown District', 'BNTCTYLIB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.990605', '2025-04-01 01:55:38.990609', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (16, 2017, 'Unknown District', 'WBNTFIRE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:39.077069', '2025-04-01 01:55:39.077073', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (17, 2018, 'Unknown District', 'BNTCTY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:39.163035', '2025-04-01 01:55:39.163039', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (20, 2018, 'Unknown District', 'PROSSER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:39.421429', '2025-04-01 01:55:39.421432', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (21, 2018, 'Unknown District', 'RICH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:39.507568', '2025-04-01 01:55:39.507571', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (22, 2018, 'Unknown District', 'WRICH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:39.594030', '2025-04-01 01:55:39.594033', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (30, 2018, 'Unknown District', 'KENNHOSP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.281395', '2025-04-01 01:55:40.281399', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (31, 2018, 'Unknown District', 'MCLIB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.367047', '2025-04-01 01:55:40.367050', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (23, 2018, 'Unknown District', 'COUNTY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:39.680518', '2025-04-01 01:55:39.680522', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (24, 2018, 'Unknown District', 'COUNTY_2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:39.767160', '2025-04-01 01:55:39.767164', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (25, 2018, 'Unknown District', 'COUNTY_3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:39.852746', '2025-04-01 01:55:39.852749', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (6, 2017, 'Unknown District', 'COUNTY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.215009', '2025-04-01 01:55:38.215014', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (7, 2017, 'Unknown District', 'COUNTY_2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.301442', '2025-04-01 01:55:38.301446', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (8, 2017, 'Unknown District', 'COUNTY_3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:38.387365', '2025-04-01 01:55:38.387369', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (26, 2018, 'Unknown District', 'ROAD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:39.938550', '2025-04-01 01:55:39.938554', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (27, 2018, 'Unknown District', 'ROAD_2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.024306', '2025-04-01 01:55:40.024309', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (2, 2017, 'Unknown District', 'KENN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:37.870906', '2025-04-01 01:55:37.870909', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (3, 2017, 'Unknown District', 'KENN_2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:37.956854', '2025-04-01 01:55:37.956858', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (32, 2018, 'Unknown District', 'PORTBNT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.453572', '2025-04-01 01:55:40.453575', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (18, 2018, 'Unknown District', 'KENN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:39.249332', '2025-04-01 01:55:39.249336', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (19, 2018, 'Unknown District', 'KENN_2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:39.335474', '2025-04-01 01:55:39.335477', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (28, 2018, 'Unknown District', 'FIRE1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.110031', '2025-04-01 01:55:40.110035', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (29, 2018, 'Unknown District', 'FIRE1_2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.195758', '2025-04-01 01:55:40.195761', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (34, 2018, 'Unknown District', 'PTKEN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.625683', '2025-04-01 01:55:40.625687', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (35, 2018, 'Unknown District', 'BNTCTYLIB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.711545', '2025-04-01 01:55:40.711548', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (36, 2018, 'Unknown District', 'WBNTFIRE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.797630', '2025-04-01 01:55:40.797634', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (37, 2019, 'Unknown District', 'BNTCTY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.883502', '2025-04-01 01:55:40.883505', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (40, 2019, 'Unknown District', 'PROSSER', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:41.141665', '2025-04-01 01:55:41.141668', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (41, 2019, 'Unknown District', 'RICH', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:41.227801', '2025-04-01 01:55:41.227820', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (45, 2019, 'Unknown District', 'ROAD', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:41.574313', '2025-04-01 01:55:41.574316', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (46, 2019, 'Unknown District', 'FIRE1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:41.660196', '2025-04-01 01:55:41.660200', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (47, 2019, 'Unknown District', 'FIRE2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:41.746523', '2025-04-01 01:55:41.746527', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (48, 2019, 'Unknown District', 'FIRE6', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:41.832409', '2025-04-01 01:55:41.832413', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (49, 2019, 'Unknown District', 'KENNHOSP', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:41.918378', '2025-04-01 01:55:41.918381', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (50, 2019, 'Unknown District', 'MCLIB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:42.005045', '2025-04-01 01:55:42.005051', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (53, 2019, 'Unknown District', 'PTKEN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:42.264905', '2025-04-01 01:55:42.264911', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (54, 2019, 'Unknown District', 'BNTCTYLIB', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:42.351344', '2025-04-01 01:55:42.351348', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (55, 2019, 'Unknown District', 'WBNTFIRE', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:42.438178', '2025-04-01 01:55:42.438183', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (42, 2019, 'Unknown District', 'COUNTY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:41.313792', '2025-04-01 01:55:41.313795', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (43, 2019, 'Unknown District', 'COUNTY_2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:41.400788', '2025-04-01 01:55:41.400792', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (44, 2019, 'Unknown District', 'COUNTY_3', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:41.488610', '2025-04-01 01:55:41.488613', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (33, 2018, 'Unknown District', 'PORTBNT_2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.539519', '2025-04-01 01:55:40.539523', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (51, 2019, 'Unknown District', 'PORTBNT', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:42.091703', '2025-04-01 01:55:42.091707', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (52, 2019, 'Unknown District', 'PORTBNT_2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:42.178239', '2025-04-01 01:55:42.178243', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (38, 2019, 'Unknown District', 'KENN', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:40.969514', '2025-04-01 01:55:40.969518', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (39, 2019, 'Unknown District', 'KENN_2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:41.055914', '2025-04-01 01:55:41.055916', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (56, 2025, 'Unknown District', 'COUNTY', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:42.525096', '2025-04-01 01:55:42.525101', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (57, 2025, 'Unknown District', 'COUNTY_2', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2025-04-01 01:55:42.611016', '2025-04-01 01:55:42.611019', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (58, 2017, 'BNTCTYADR', 'BNTCTYADR', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:03:28.319704', '2025-04-02 00:03:28.319707', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (59, 2017, 'KENADR', 'KENADR', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:03:28.601217', '2025-04-02 00:03:28.601220', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (60, 2017, 'KENFIREPEN', 'KENFIREPEN', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:03:28.888894', '2025-04-02 00:03:28.888897', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (61, 2017, 'RICHADR', 'RICHADR', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:03:29.361890', '2025-04-02 00:03:29.361893', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (62, 2017, 'CNYADMR', 'CNYADMR', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:03:29.638276', '2025-04-02 00:03:29.638279', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (63, 2017, 'CNYHMNSVCS', 'CNYHMNSVCS', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:03:29.914621', '2025-04-02 00:03:29.914624', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (64, 2017, 'CNYVET', 'CNYVET', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:03:30.190778', '2025-04-02 00:03:30.190782', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (65, 2017, 'DIVROAD', 'DIVROAD', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:03:30.468969', '2025-04-02 00:03:30.468972', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (66, 2017, 'FIRE1BD', 'FIRE1BD', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:03:30.744464', '2025-04-02 00:03:30.744467', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (67, 2017, 'KENNHOSPR', 'KENNHOSPR', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:04:17.006610', '2025-04-02 00:04:17.006613', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (68, 2017, 'LIBADR', 'LIBADR', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:04:17.308518', '2025-04-02 00:04:17.308521', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (69, 2017, 'PTBNT11AB', 'PTBNT11AB', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:04:17.605024', '2025-04-02 00:04:17.605028', NULL, NULL);
INSERT INTO tax_district (id, year, district_name, district_code, district_type, county, state, description, is_active, contact_name, contact_email, contact_phone, statutory_limit, created_at, updated_at, created_by_id, updated_by_id) VALUES (70, 2017, 'PTKENADR', 'PTKENADR', NULL, NULL, NULL, NULL, True, NULL, NULL, NULL, NULL, '2025-04-02 00:04:17.898901', '2025-04-02 00:04:17.898904', NULL, NULL);

-- Table structure for tax_district_old
DROP TABLE IF EXISTS tax_district_old CASCADE;
CREATE TABLE tax_district_old (
    id integer NOT NULL DEFAULT nextval('tax_district_id_seq'::regclass),
    year integer NOT NULL,
    levy_code character varying(20) NOT NULL,
    linked_levy_code character varying(20) NOT NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL,
    district_name character varying(255) NOT NULL DEFAULT 'Unknown District'::character varying,
    statutory_limit double precision NULL,
    tax_district_id character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

-- Data for tax_district_old
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (1, 2017, 'BNTCTY', 'BNTCTYADR', '2025-04-01 01:55:37.778879', '2025-04-01 01:55:37.778884', 'Unknown District', NULL, '501');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (4, 2017, 'PROSSER', 'PROSSER AR', '2025-04-01 01:55:38.042836', '2025-04-01 01:55:38.042841', 'Unknown District', NULL, '503');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (5, 2017, 'RICH', 'RICHADR', '2025-04-01 01:55:38.129195', '2025-04-01 01:55:38.129198', 'Unknown District', NULL, '504');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (9, 2017, 'ROAD', 'DIVROAD', '2025-04-01 01:55:38.474914', '2025-04-01 01:55:38.474919', 'Unknown District', NULL, '507');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (10, 2017, 'FIRE1', 'FIRE1BD', '2025-04-01 01:55:38.560981', '2025-04-01 01:55:38.560984', 'Unknown District', NULL, '513');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (11, 2017, 'KENNHOSP', 'KENNHOSPR', '2025-04-01 01:55:38.646852', '2025-04-01 01:55:38.646856', 'Unknown District', NULL, '519');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (12, 2017, 'MCLIB', 'LIBADR', '2025-04-01 01:55:38.732711', '2025-04-01 01:55:38.732714', 'Unknown District', NULL, '525');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (13, 2017, 'PORTBNT', 'PTBNT11AB', '2025-04-01 01:55:38.818510', '2025-04-01 01:55:38.818513', 'Unknown District', NULL, '528');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (14, 2017, 'PTKEN', 'PTKENADR', '2025-04-01 01:55:38.904352', '2025-04-01 01:55:38.904356', 'Unknown District', NULL, '529');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (15, 2017, 'BNTCTYLIB', 'BCTYLIBADR', '2025-04-01 01:55:38.990605', '2025-04-01 01:55:38.990609', 'Unknown District', NULL, '155172');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (16, 2017, 'WBNTFIRE', 'WBRFAADR', '2025-04-01 01:55:39.077069', '2025-04-01 01:55:39.077073', 'Unknown District', NULL, '218537');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (17, 2018, 'BNTCTY', 'BNTCTYADR', '2025-04-01 01:55:39.163035', '2025-04-01 01:55:39.163039', 'Unknown District', NULL, '501');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (20, 2018, 'PROSSER', 'PROSSER AR', '2025-04-01 01:55:39.421429', '2025-04-01 01:55:39.421432', 'Unknown District', NULL, '503');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (21, 2018, 'RICH', 'RICHADR', '2025-04-01 01:55:39.507568', '2025-04-01 01:55:39.507571', 'Unknown District', NULL, '504');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (22, 2018, 'WRICH', 'WRICHADR', '2025-04-01 01:55:39.594030', '2025-04-01 01:55:39.594033', 'Unknown District', NULL, '505');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (30, 2018, 'KENNHOSP', 'KENNHOSPR', '2025-04-01 01:55:40.281395', '2025-04-01 01:55:40.281399', 'Unknown District', NULL, '519');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (31, 2018, 'MCLIB', 'LIBADR', '2025-04-01 01:55:40.367047', '2025-04-01 01:55:40.367050', 'Unknown District', NULL, '525');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (23, 2018, 'COUNTY', 'CNYADMR', '2025-04-01 01:55:39.680518', '2025-04-01 01:55:39.680522', 'Unknown District', NULL, '506');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (24, 2018, 'COUNTY_2', 'CNYHMNSVCS', '2025-04-01 01:55:39.767160', '2025-04-01 01:55:39.767164', 'Unknown District', NULL, '506');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (25, 2018, 'COUNTY_3', 'CNYVET', '2025-04-01 01:55:39.852746', '2025-04-01 01:55:39.852749', 'Unknown District', NULL, '506');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (6, 2017, 'COUNTY', 'CNYADMR', '2025-04-01 01:55:38.215009', '2025-04-01 01:55:38.215014', 'Unknown District', NULL, '506');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (7, 2017, 'COUNTY_2', 'CNYHMNSVCS', '2025-04-01 01:55:38.301442', '2025-04-01 01:55:38.301446', 'Unknown District', NULL, '506');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (8, 2017, 'COUNTY_3', 'CNYVET', '2025-04-01 01:55:38.387365', '2025-04-01 01:55:38.387369', 'Unknown District', NULL, '506');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (26, 2018, 'ROAD', 'CNYRDAD', '2025-04-01 01:55:39.938550', '2025-04-01 01:55:39.938554', 'Unknown District', NULL, '507');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (27, 2018, 'ROAD_2', 'DIVROAD', '2025-04-01 01:55:40.024306', '2025-04-01 01:55:40.024309', 'Unknown District', NULL, '507');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (2, 2017, 'KENN', 'KENADR', '2025-04-01 01:55:37.870906', '2025-04-01 01:55:37.870909', 'Unknown District', NULL, '502');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (3, 2017, 'KENN_2', 'KENFIREPEN', '2025-04-01 01:55:37.956854', '2025-04-01 01:55:37.956858', 'Unknown District', NULL, '502');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (32, 2018, 'PORTBNT', 'PTBNT11AB', '2025-04-01 01:55:40.453572', '2025-04-01 01:55:40.453575', 'Unknown District', NULL, '528');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (18, 2018, 'KENN', 'KENADR', '2025-04-01 01:55:39.249332', '2025-04-01 01:55:39.249336', 'Unknown District', NULL, '502');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (19, 2018, 'KENN_2', 'KENFIREPEN', '2025-04-01 01:55:39.335474', '2025-04-01 01:55:39.335477', 'Unknown District', NULL, '502');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (28, 2018, 'FIRE1', 'FIRE1ADR', '2025-04-01 01:55:40.110031', '2025-04-01 01:55:40.110035', 'Unknown District', NULL, '513');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (29, 2018, 'FIRE1_2', 'FIRE1BD', '2025-04-01 01:55:40.195758', '2025-04-01 01:55:40.195761', 'Unknown District', NULL, '513');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (34, 2018, 'PTKEN', 'PTKENADR', '2025-04-01 01:55:40.625683', '2025-04-01 01:55:40.625687', 'Unknown District', NULL, '529');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (35, 2018, 'BNTCTYLIB', 'BCTYLIBADR', '2025-04-01 01:55:40.711545', '2025-04-01 01:55:40.711548', 'Unknown District', NULL, '155172');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (36, 2018, 'WBNTFIRE', 'WBRFAADR', '2025-04-01 01:55:40.797630', '2025-04-01 01:55:40.797634', 'Unknown District', NULL, '218537');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (37, 2019, 'BNTCTY', 'BNTCTYADR', '2025-04-01 01:55:40.883502', '2025-04-01 01:55:40.883505', 'Unknown District', NULL, '501');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (40, 2019, 'PROSSER', 'PROSSER AR', '2025-04-01 01:55:41.141665', '2025-04-01 01:55:41.141668', 'Unknown District', NULL, '503');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (41, 2019, 'RICH', 'RICHADR', '2025-04-01 01:55:41.227801', '2025-04-01 01:55:41.227820', 'Unknown District', NULL, '504');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (45, 2019, 'ROAD', 'DIVROAD', '2025-04-01 01:55:41.574313', '2025-04-01 01:55:41.574316', 'Unknown District', NULL, '507');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (46, 2019, 'FIRE1', 'FIRE1ADR', '2025-04-01 01:55:41.660196', '2025-04-01 01:55:41.660200', 'Unknown District', NULL, '513');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (47, 2019, 'FIRE2', 'FIRE2ADR', '2025-04-01 01:55:41.746523', '2025-04-01 01:55:41.746527', 'Unknown District', NULL, '514');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (48, 2019, 'FIRE6', 'FIRE6AR', '2025-04-01 01:55:41.832409', '2025-04-01 01:55:41.832413', 'Unknown District', NULL, '518');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (49, 2019, 'KENNHOSP', 'KENNHOSPR', '2025-04-01 01:55:41.918378', '2025-04-01 01:55:41.918381', 'Unknown District', NULL, '519');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (50, 2019, 'MCLIB', 'LIBADR', '2025-04-01 01:55:42.005045', '2025-04-01 01:55:42.005051', 'Unknown District', NULL, '525');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (53, 2019, 'PTKEN', 'PTKENADR', '2025-04-01 01:55:42.264905', '2025-04-01 01:55:42.264911', 'Unknown District', NULL, '529');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (54, 2019, 'BNTCTYLIB', 'BCTYLIBADR', '2025-04-01 01:55:42.351344', '2025-04-01 01:55:42.351348', 'Unknown District', NULL, '155172');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (55, 2019, 'WBNTFIRE', 'WBRFAADR', '2025-04-01 01:55:42.438178', '2025-04-01 01:55:42.438183', 'Unknown District', NULL, '218537');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (42, 2019, 'COUNTY', 'CNYADMR', '2025-04-01 01:55:41.313792', '2025-04-01 01:55:41.313795', 'Unknown District', NULL, '506');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (43, 2019, 'COUNTY_2', 'CNYHMNSVCS', '2025-04-01 01:55:41.400788', '2025-04-01 01:55:41.400792', 'Unknown District', NULL, '506');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (44, 2019, 'COUNTY_3', 'CNYVET', '2025-04-01 01:55:41.488610', '2025-04-01 01:55:41.488613', 'Unknown District', NULL, '506');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (33, 2018, 'PORTBNT_2', 'PTBNTADR', '2025-04-01 01:55:40.539519', '2025-04-01 01:55:40.539523', 'Unknown District', NULL, '528');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (51, 2019, 'PORTBNT', 'PTBNT11AB', '2025-04-01 01:55:42.091703', '2025-04-01 01:55:42.091707', 'Unknown District', NULL, '528');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (52, 2019, 'PORTBNT_2', 'PTBNTADR', '2025-04-01 01:55:42.178239', '2025-04-01 01:55:42.178243', 'Unknown District', NULL, '528');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (38, 2019, 'KENN', 'KENADR', '2025-04-01 01:55:40.969514', '2025-04-01 01:55:40.969518', 'Unknown District', NULL, '502');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (39, 2019, 'KENN_2', 'KENFIREPEN', '2025-04-01 01:55:41.055914', '2025-04-01 01:55:41.055916', 'Unknown District', NULL, '502');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (56, 2025, 'COUNTY', 'CNYHMNSVCS', '2025-04-01 01:55:42.525096', '2025-04-01 01:55:42.525101', 'Unknown District', NULL, '506');
INSERT INTO tax_district_old (id, year, levy_code, linked_levy_code, created_at, updated_at, district_name, statutory_limit, tax_district_id) VALUES (57, 2025, 'COUNTY_2', 'CNYVET', '2025-04-01 01:55:42.611016', '2025-04-01 01:55:42.611019', 'Unknown District', NULL, '506');

-- Table structure for user
DROP TABLE IF EXISTS user CASCADE;
CREATE TABLE user (
    id integer NOT NULL DEFAULT nextval('user_id_seq'::regclass),
    username character varying(64) NOT NULL,
    email character varying(120) NOT NULL,
    password_hash character varying(256) NOT NULL,
    first_name character varying(64) NULL,
    last_name character varying(64) NULL,
    is_active boolean NULL,
    is_admin boolean NULL,
    last_login timestamp without time zone NULL,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL,
    created_by_id integer NULL,
    updated_by_id integer NULL,
    PRIMARY KEY (id)
);

-- Data for user
INSERT INTO user (user) VALUES ('neondb_owner');

-- Foreign Key Constraints
ALTER TABLE ai_analysis_request ADD CONSTRAINT ai_analysis_request_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE ai_analysis_request ADD CONSTRAINT ai_analysis_request_updated_by_id_fkey FOREIGN KEY (updated_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE ai_analysis_request ADD CONSTRAINT ai_analysis_request_user_id_fkey FOREIGN KEY (user_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE analysis_result ADD CONSTRAINT analysis_result_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE analysis_result ADD CONSTRAINT analysis_result_updated_by_id_fkey FOREIGN KEY (updated_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE analysis_result ADD CONSTRAINT analysis_result_user_id_fkey FOREIGN KEY (user_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE bill_impact_tax_code ADD CONSTRAINT bill_impact_tax_code_evaluation_id_fkey FOREIGN KEY (evaluation_id) REFERENCES bill_impact_evaluation(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE compliance_check ADD CONSTRAINT compliance_check_tax_code_id_fkey FOREIGN KEY (tax_code_id) REFERENCES tax_code(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE compliance_issue ADD CONSTRAINT compliance_issue_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE compliance_issue ADD CONSTRAINT compliance_issue_resolved_by_id_fkey FOREIGN KEY (resolved_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE compliance_issue ADD CONSTRAINT compliance_issue_tax_district_id_fkey FOREIGN KEY (tax_district_id) REFERENCES tax_district_old(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE compliance_issue ADD CONSTRAINT compliance_issue_updated_by_id_fkey FOREIGN KEY (updated_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE forecast ADD CONSTRAINT forecast_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE forecast ADD CONSTRAINT forecast_tax_code_id_fkey FOREIGN KEY (tax_code_id) REFERENCES tax_code(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE forecast ADD CONSTRAINT forecast_tax_district_id_fkey FOREIGN KEY (tax_district_id) REFERENCES tax_district_old(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE forecast ADD CONSTRAINT forecast_updated_by_id_fkey FOREIGN KEY (updated_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE forecast ADD CONSTRAINT forecast_user_id_fkey FOREIGN KEY (user_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE glossary_term ADD CONSTRAINT glossary_term_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE glossary_term ADD CONSTRAINT glossary_term_updated_by_id_fkey FOREIGN KEY (updated_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE import_log ADD CONSTRAINT fk_import_log_user FOREIGN KEY (user_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE levy_rate ADD CONSTRAINT levy_rate_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE levy_rate ADD CONSTRAINT levy_rate_tax_district_id_fkey FOREIGN KEY (tax_district_id) REFERENCES tax_district_old(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE levy_rate ADD CONSTRAINT levy_rate_updated_by_id_fkey FOREIGN KEY (updated_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE levy_scenario_adjustment ADD CONSTRAINT levy_scenario_adjustment_scenario_id_fkey FOREIGN KEY (scenario_id) REFERENCES levy_scenario(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE levy_scenario_adjustment ADD CONSTRAINT levy_scenario_adjustment_tax_code_id_fkey FOREIGN KEY (tax_code_id) REFERENCES tax_code(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE scheduled_report ADD CONSTRAINT scheduled_report_template_id_fkey FOREIGN KEY (template_id) REFERENCES report_template(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE system_setting ADD CONSTRAINT system_setting_updated_by_id_fkey FOREIGN KEY (updated_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE tax_code_historical_rate ADD CONSTRAINT tax_code_historical_rate_tax_code_id_fkey FOREIGN KEY (tax_code_id) REFERENCES tax_code(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE user ADD CONSTRAINT user_created_by_id_fkey FOREIGN KEY (created_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE user ADD CONSTRAINT user_updated_by_id_fkey FOREIGN KEY (updated_by_id) REFERENCES user(id) ON UPDATE NO ACTION ON DELETE NO ACTION;

-- Sequences
SELECT setval('property_id_seq', 97, true);
SELECT setval('tax_code_id_seq', 17, true);
SELECT setval('import_log_id_seq', 3, true);
SELECT setval('export_log_id_seq', 2, true);
SELECT setval('tax_district_id_seq', 62, true);
SELECT setval('tax_code_historical_rate_id_seq', 1, true);
SELECT setval('bill_impact_evaluation_id_seq', 1, true);
SELECT setval('audit_log_id_seq', 1, true);
SELECT setval('data_archive_id_seq', 1, true);
SELECT setval('compliance_report_id_seq', 1, true);
SELECT setval('bill_impact_tax_code_id_seq', 1, true);
SELECT setval('forecast_model_id_seq', 1, true);
SELECT setval('district_forecast_id_seq', 1, true);
SELECT setval('report_template_id_seq', 1, true);
SELECT setval('scheduled_report_id_seq', 1, true);
SELECT setval('compliance_check_id_seq', 1, true);
SELECT setval('levy_scenario_id_seq', 1, true);
SELECT setval('levy_scenario_adjustment_id_seq', 1, true);
SELECT setval('user_id_seq', 1, true);
SELECT setval('levy_rate_id_seq', 1, true);
SELECT setval('forecast_id_seq', 1, true);
SELECT setval('compliance_issue_id_seq', 1, true);
SELECT setval('glossary_term_id_seq', 1, true);
SELECT setval('analysis_result_id_seq', 1, true);
SELECT setval('system_setting_id_seq', 1, true);
SELECT setval('ai_analysis_request_id_seq', 1, true);
SELECT setval('tax_district_temp_id_seq', 36, true);
