name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Helm cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/helm
          key: ${{ runner.os }}-helm-${{ hashFiles('infra/helm/**/*.yaml') }}
          restore-keys: |
            ${{ runner.os }}-helm-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run lint & type-check
        run: |
          npm run lint
          npm run type-check

      - name: Run unit tests
        run: npm test

      - name: Security audit
        run: npm audit --audit-level=moderate

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Helm lint all charts
        working-directory: infra/helm
        run: |
          for d in *; do
            if [ -f "$d/Chart.yaml" ]; then
              echo "→ Linting chart: $d"
              helm lint "$d" --strict
            fi
          done

  validate-migrations:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      
      - name: Install PostGIS in PostgreSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client postgis
          PGPASSWORD=postgres psql -h localhost -U postgres -d testdb -c "CREATE EXTENSION postgis;"
          echo "PostGIS extension installed."
      
      - name: Download Flyway
        run: |
          wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/9.4.0/flyway-commandline-9.4.0-linux-x64.tar.gz | tar xvz
          sudo ln -s $(pwd)/flyway-9.4.0/flyway /usr/local/bin/flyway
      
      - name: Validate Flyway migrations
        run: |
          cd db-migrations
          flyway validate -url=jdbc:postgresql://localhost:5432/testdb -user=postgres -password=postgres -locations=filesystem:migrations
      
      - name: Run Flyway clean and migrate to test migrations
        run: |
          cd db-migrations
          flyway clean -url=jdbc:postgresql://localhost:5432/testdb -user=postgres -password=postgres
          flyway migrate -url=jdbc:postgresql://localhost:5432/testdb -user=postgres -password=postgres -locations=filesystem:migrations
          
          # Verify PostGIS is working correctly
          PGPASSWORD=postgres psql -h localhost -U postgres -d testdb -c "SELECT postgis_version();"