name: Import API Tests

on:
  push:
    branches: [main, develop]
    paths:
      - 'server/routes/import.ts'
      - 'server/import-controller.ts'
      - 'packages/ui/src/components/ImportWizard/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'server/routes/import.ts'
      - 'server/import-controller.ts'
      - 'packages/ui/src/components/ImportWizard/**'
  workflow_dispatch:

jobs:
  test-import-api:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
      
      - name: Start server
        run: |
          npm run start:server &
          sleep 10
      
      - name: Run Import API tests
        run: |
          chmod +x ./devops/test-import-api.sh
          ./devops/test-import-api.sh http://localhost:5000
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: import-api-test-results
          path: ./temp/test-results
      
      - name: Notify on failure
        if: failure()
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          details: Import API tests failed
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          title: TerraFusion Import API Tests Failed